on:
  push:
    branches:
      - main
      - test

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Create Properties & Build
        run: |
          mkdir -p src/main/resources
          if [ "${{ github.base_ref }}" = "main" ]; then
            echo "${{ secrets.APPLICATION_PROD_YML }}" > src/main/resources/application-prod.yml
            ./gradlew build -Dspring.profiles.active=prod
            echo "ENV=prod" >> $GITHUB_ENV # 다음 스텝에서 쓰기 위해 환경변수 저장
          else
            echo "${{ secrets.APPLICATION_DEV_YML }}" > src/main/resources/application-dev.yml
            ./gradlew build -Dspring.profiles.active=dev
            echo "ENV=dev" >> $GITHUB_ENV
          fi

      # 2. 도커 로그인
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # 3. 도커 이미지 빌드 및 푸시
      - name: Build and push Docker image
        run: |
          # 이미지 태그에 브랜치 환경(prod/dev) 표시
          docker build -t ${{ secrets.DOCKER_USERNAME }}/api-test:${{ env.ENV }} .
          docker push ${{ secrets.DOCKER_USERNAME }}/api-test:${{ env.ENV }}

      # 4. CD ssm이 22번포트를 닫고있기때문에 이방법 사용
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-2

      - name: Deploy to EC2 via SSM
        run: |
          aws ssm send-command \
            --instance-ids "${{ secrets.EC2_INSTANCE_ID }}" \
            --document-name "AWS-RunShellScript" \
            --comment "Deploying ${{ env.ENV }} environment" \
            --parameters 'commands=[
              "cd /home/ssm-user/api-test",
              "docker compose pull",
              "docker compose up -d"
            ]'